With Pre-Processing

In [58]:
import pandas as pd

In [59]:
df = pd.read_csv("Car_Purchasing.csv")

In [60]:
df

Annual Salary  Car Purchase Amount
0     62812.09301          35321.45877
1     66646.89292          45115.52566
2     53798.55112          42925.70921
3     79370.03798          67422.36313
4     59729.15130          55915.46248
5     68499.85162          56611.99784
6     39814.52200          28925.70549
7     51752.23445          47434.98265
8     58139.25910          48013.61410
9     53457.10132          38189.50601
10    73348.70745          59045.51309
11    55421.65733          42288.81046
12    37336.33830          28700.03340
13    68304.47298          49258.87571
14    72776.00382          49510.03356

In [61]:
X = df.iloc[:,0].values
y = df.iloc[:,1].values
X

array([62812.09301, 66646.89292, 53798.55112, 79370.03798, 59729.1513 ,
       68499.85162, 39814.522  , 51752.23445, 58139.2591 , 53457.10132,
       73348.70745, 55421.65733, 37336.3383 , 68304.47298, 72776.00382])

In [62]:
y

array([35321.45877, 45115.52566, 42925.70921, 67422.36313, 55915.46248,
       56611.99784, 28925.70549, 47434.98265, 48013.6141 , 38189.50601,
       59045.51309, 42288.81046, 28700.0334 , 49258.87571, 49510.03356])

In [63]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2, random_state = 0)

In [64]:
import numpy as np
from sklearn.preprocessing import StandardScaler
X_train = X_train.reshape(-1, 1)
X_test = X_test.reshape(-1, 1)
sc_X = StandardScaler()
X_train_scaled = sc_X.fit_transform(X_train)
X_test_scaled = sc_X.transform(X_test)
print(X_test_scaled)


[[ 0.46660317]
 [-1.912262  ]
 [-0.28765421]]


In [65]:
X_train_scaled

array([[-0.70275812],
       [ 1.00998894],
       [-0.14669987],
       [-0.67248636],
       [ 0.61355848],
       [ 1.06076286],
       [-0.85390572],
       [-0.52858738],
       [ 1.59459319],
       [ 0.12662308],
       [ 0.63088008],
       [-2.13196919]])

In [66]:
import numpy as np
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [67]:
y_pred

array([51708.44096861, 31367.84372013, 45259.12817452])

In [68]:
y_test

array([45115.52566, 28925.70549, 48013.6141 ])